const {botName,emoji,ownerName,bloom,mode,devName,prefix,cpYear}=require("./setup");
const footer =`> (c) ${cpYear} @${devName} - ${ownerName} - ☁️ •|•`;
module.exports = {
    about: `_Hi, I am ${botName} ${emoji}_\n> A WhatsApp multidevice AI written in JavaScrip based on Baileys. I was developed by Master ${ownerName} and LICENSED under ISC licensing policy at ColdNode Labs (Naivasha, Kenya), I am one of the most current advanced Artificial Intelligence user-bot model with more than 400 features and functionalities, you can check other productions from my developer on GitHub (${devName}). You can contact dev ${devName} by opening a ticket here: \n${emoji} To open a ticket send: *(${prefix}ticket)*`,
    ticket: `Your ticket have been created succsessfully.\n_${devName} will be back to you shortly, in the meantime, check the (${prefix}menu) to see available commands, I\`m glad to serve you_`,
    bloom: `╭────${emoji} ${botName}─────\n│   > Version: ${bloom.version} beta\n│   > Global prefix: ${prefix}\n│    _A reason to imagine_\n│    _Operating mode: ${mode}_\n╰─────────────────────\n${footer}`,
    powered: `Powered By ${devName}`,
    admin: "_This command is meant for group admins only!_",
    owner: `This Command is meant for ${botName} owner only!`,
    autorestart: `${botName} Will restart automatically to apply changes, if you don\'t want automatic restarts, you can disable in config file.`,
    manualrestart: `You need to restart ${botName} manually to apply changes, If you want automatic restarts, you can enable in config file.`,
    norestart: `_🚫 Only ${botName} owner can restart bot_`,
    shut: `Shutting down.... You will need to start the ${botName} manually!`,
    noshut:`Unauthorized`,
    ping: "_Response time:_",
    pong: "_Pong!_",
    search: "_Searching for results, please wait..._",
    nosearch: "_No matching content found for your query_",
    broadcast: "_Broadcast sent succsessfully_",
    restarting: `╭────────────────────\n│> *🔁 Restarting ${emoji} ${botName}....*\n│ _I will notify you once I\'m online_\n│ Restart manually in case I fail.\n╰────────────────────── 🚀`,
    group: "_This command can only be used in group chats._",
    agenda: `_Hold on, that is a private agenda unless you are ${botName} owner, you can\`t do that in a group_`,
    ticketarg: `Please write your issue or ticket ID\nE.g:\n!ticket something is not ok with this... or\n!ticket BB-0000A`,
    botadmin: `_${botName} needs to be admin first!_\n_I can\`t perform that action_`,
    youadmin: "_You are not an admin!\nYou can\`t use that command_",
    nsfwoff: `_NSFW are not enabled in current group!_\n_To enable use *${prefix}act nsfw*_`,
    nsfwon: `_NSFW are already enabled in current group!_\n_To disable use *${prefix}deact nsfw*_`,
    games: `_Games are not enabled in current group!_\n_To enable use *${prefix}act games*_`,
    economy: `_Economy is not enabled in current group!_\n_To enable use *${prefix}act economy*_`,
    act: `_A second parameter is required!_\n_> ${prefix}act (economy,games,nsfw,welcome,left) chose one_`,
    deact: `_A second parameter is required!_\n_> ${prefix}deact (economy,games,nsfw,welcome,left) chose one_`,
    add: `_To add a user in this group._\n_Type the command as follows ;_\n\n*_${prefix}add 2547xxxxxxxx_*`,
    joinlink: `_I need a group link or group code_\n\n_${prefix}join your_valid_group_link_or_code_here_`,
    error404: `_Command not found...! in database_\n\n*_Try ${prefix}menu_* to view available commands`,
    error: `An error occured..! I will notify the Developer`,
    bug: "*An error occurred..!*\n\n_I have sent a report to bot developer(s)_",
    not_a_repo: '❌ This folder is not a Git repository.',
    no_updates: '✅ Already up to date!',
    pull_success: '✅ Pulled latest changes successfully!',
    pull_failed: '❌ Git pull failed!',
    restart_later: '⏰ Restart cancelled. You can restart manually later.',
    restarting_now: '♻️ Restarting the bot now...',
    restart_failed: '❌ Restart failed!',
    installing_dependencies: '📦 Installing dependencies...',
    install_failed: '❌ Failed to install dependencies!',
    caption: footer,
};
